name: Build Check

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  makeTest:
    strategy:
      matrix:
        runs-on-arch: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runs-on-arch }}
    container: 
      image: quay.io/rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v4
      - name: Specify Build Target
        run: |
          echo "SPECIFICTARGET=github-release" >> $GITHUB_ENV
      - name: Test Makefile Targets
        run: ci/testbuilding.sh

  buildTest:
    needs: makeTest
    strategy:
      matrix:
        runs-on-arch: [ubuntu-latest, ubuntu-24.04-arm]
        os: [fedora]
        version: [39, 40, 41]
        dockernamespace: [quay.io/fedora/fedora]
        include:
          - os: centos-stream
            version: stream9
            dockernamespace: quay.io/centos/centos
          - os: rocky
            version: 9
            dockernamespace: quay.io/rockylinux/rockylinux
          - os: almalinux
            version: 9
            dockernamespace: quay.io/almalinux/almalinux
    runs-on: ${{ matrix.runs-on-arch }}
    container: 
      image: ${{ matrix.dockernamespace }}:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Specify Build Target
        run: |
          echo "SPECIFICTARGET=github-release" >> $GITHUB_ENV
          
      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV

      - name: Run CI
        run: ci/${{ matrix.os }}.sh

  mockTest:
    needs: makeTest
    strategy:
      matrix:
        runs-on-arch: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runs-on-arch }}
    container: 
      image: quay.io/rockylinux/rockylinux:9
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Test Mock Build From Spec
        run: |
          echo "Install Mock"
          dnf -y install epel-release
          dnf -y install mock gcc gcc-c++ glibc-devel.x86_64 libdrm-devel rpm-build make wget
          echo "Get source files"
          make srpm-github
          echo "Run mock build"
          mock -r rocky+epel-9-x86_64 --define="_github 1" --spec="displaylink.spec" --sources="."
