name: Devel Branch Build

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Bemerkung'
        required: false
  pull_request:
    branches: [ master ]

jobs:
  develBuild:
    runs-on: ubuntu-latest
    container: 
      image: ${{ matrix.dockernamespace }}:${{ matrix.version }}
    strategy:
      matrix:
        include:
          - os: fedora
            version: 36
            dockernamespace: fedora
          - os: fedora
            version: 37
            dockernamespace: fedora
          - os: fedora
            version: 38
            dockernamespace: fedora

    steps:
      - uses: actions/checkout@v3

      - name: Specify Build Target
        run: |
          echo "SPECIFICTARGET=devel" >> $GITHUB_ENV

      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV

      - name: Run CI
        if: matrix.version < 37 || startsWith(matrix.os, 'centos')
        run: ci/${{ matrix.os }}.sh
      
      - name: Run CI (Fedora 37+)
        if: matrix.os == 'fedora' && matrix.version > 36
        run: ci/${{ matrix.os }}37plus.sh
