name: Main Branch Build

on:
  schedule:
    - cron: '30 5 * * 1'

jobs:
  mainBuild:
    strategy:
      matrix:
        runs-on-os: [ubuntu-latest, ubuntu-24.04-arm]
        os: [fedora]
        version: [39, 40, 41]
        dockernamespace: [quay.io/fedora/fedora]
        include:
          - os: centos-stream
            version: stream9
            dockernamespace: quay.io/centos/centos
          - os: rocky
            version: 9
            dockernamespace: quay.io/rockylinux/rockylinux
          - os: almalinux
            version: 9
            dockernamespace: quay.io/almalinux/almalinux
    runs-on: ${{ matrix.runs-on-os }}
    container: 
        image: ${{ matrix.dockernamespace }}:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Specify Build Target
        run: |
          echo "SPECIFICTARGET=main" >> $GITHUB_ENV

      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV

      - name: Run CI
        run: ci/${{ matrix.os }}.sh
