name: Create Release Assets

on:
  release:
    types:
      - published

jobs:  
  buildrpms:
    runs-on: ubuntu-latest
    container: 
      image: ${{ matrix.dockernamespace }}:${{ matrix.version }}
    strategy:
      matrix:
        include:
        - os: fedora
          version: 36
          dockernamespace: fedora
        - os: fedora
          version: 37
          dockernamespace: fedora
        - os: fedora
          version: 38
          dockernamespace: fedora

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        run: |
          echo "VERSION=$(grep ^VERSION Makefile | awk -F:= '{print $2}' | tr -d ' ')" >> $GITHUB_ENV
      
      - name: Get release
        run: |
          echo "RELEASE=$(grep ^RELEASE Makefile | awk -F:= '{print $2}' | tr -d ' ')" >> $GITHUB_ENV

      - name: Specify A Target For make
        run: |
          echo "SPECIFICTARGET=devel" >> $GITHUB_ENV

      - name: Environment variable for setting name of RPM when using EVDI from Github
        run: |
          echo "EVDISOURCE=" >> $GITHUB_ENV

      - name: Environment variable for OS version
        run: |
          echo "OSVERSION=${{ matrix.version }}" >> $GITHUB_ENV
     
      - name: Run CI
        if: matrix.version < 37 || startsWith(matrix.os, 'centos')
        run: ci/${{ matrix.os }}.sh

      - name: Run CI (Fedora 37+)
        if: matrix.os == 'fedora' && matrix.version > 36
        run: ci/${{ matrix.os }}37plus.sh

      - name: Run build
        run: make

      - name: Rename files
        run : ls -la
      - run: mv displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.src.rpm ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.src.rpm
      - run: mv x86_64/displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.x86_64.rpm ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}${{ env.EVDISOURCE }}.x86_64.rpm
      - run: chown `id -u`:`id -g` -R .

      - name: Upload RPM
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}
          path: ${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm

      - name: Upload Assets To Release
        uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: '${{ matrix.os }}-${{ matrix.version }}-displaylink-${{ env.VERSION }}-${{ env.RELEASE }}.*.rpm'
          draft: false
          update_latest_release: true
          tags: true
          overwrite: true
